{{-- <script src="{{ asset('web/js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('web/styles/bootstrap4/popper.js') }}"></script>
<script src="{{ asset('web/styles/bootstrap4/bootstrap.min.js') }}"></script>
<script src="{{ asset('web/plugins/greensock/TweenMax.min.js') }}"></script>
<script src="{{ asset('web/plugins/greensock/TimelineMax.min.js') }}"></script>
<script src="{{ asset('web/plugins/scrollmagic/ScrollMagic.min.js') }}"></script>
<script src="{{ asset('web/plugins/greensock/animation.gsap.min.js') }}"></script>
<script src="{{ asset('web/plugins/greensock/ScrollToPlugin.min.js') }}"></script>
<script src="{{ asset('web/plugins/OwlCarousel2-2.2.1/owl.carousel.js') }}"></script>
<script src="{{ asset('web/plugins/scrollTo/jquery.scrollTo.min.js') }}"></script>
<script src="{{ asset('web/plugins/easing/easing.js') }}"></script>
<script src="{{ asset('web/js/custom.js') }}"></script> --}}

<script src="{{ asset('web/js/jquery-3.4.1.min.js') }}"></script>
<script src="{{ asset('web/js/jquery-ui.js') }}"></script>
<script src="{{ asset('web/js/popper.min.js') }}"></script>
<script src="{{ asset('web/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('web/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('web/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('web/js/isotope-3.0.6.min.js') }}"></script>
<script src="{{ asset('web/js/select2.min.js') }}"></script>
<script src="{{ asset('web/js/moment.min.js') }}"></script>
<script src="{{ asset('web/js/daterangepicker.js') }}"></script>
<script src="{{ asset('web/js/purecounter.js') }}"></script>
<script src="{{ asset('web/js/jquery.filer.min.js') }}"></script>
<script src="{{ asset('web/js/smooth-scrolling.js') }}"></script>
<script src="{{ asset('web/js/progresscircle.js') }}"></script>
<script src="{{ asset('web/js/main.js') }}"></script>